### PR TITLE
Add anchored headings

### PR DESCRIPTION
**Pull request by klingtnet**
See commit messages for details and `hugo serve` for a preview.

anchored headings preview

### CODE REVIEW

**Comment by miku** [comment]
Wow, thanks!

**Comment by klingtnet** [comment]
Is there anything to change or can we merge this?
I mean, styling could be improved but I've got no resources for this at the moment.

**Comment by miku** [comment]
> Is there anything to change or can we merge this?

Looks good to me.

>  I mean, styling could be improved but I've got no resources for this at the moment.

Yes, let's just merge.

In the future, it would be possible for me (or others) to create a PR on [klingtnet/simple-hugo-theme](https://github.com/klingtnet/simple-hugo-theme) to apply changes, or not?

**Comment by klingtnet** [comment]
> In the future, it would be possible for me (or others) to create a PR on klingtnet/simple-hugo-theme to apply changes, or not?

Absolutely!

**Pull request merged**
