### PR TITLE
Minor styling changes

### PR DESCRIPTION
**Pull request by klingtnet**
Damn, I somehow messed up the submodule and lost all my theme changes :cry:

### CODE REVIEW

**Comment by miku** [comment]
> Damn, I somehow messed up the submodule and lost all my theme changes.

Sorry to hear that.

**Comment by klingtnet** [comment]
So, got it fixed again.

Submodules are the worst, it's not possible to change the tracking repository of an existing submodule without removing it first.

**Comment by klingtnet** [comment]
Don't forget to `git submodule update --init` when switching to this branch.

**Comment by klingtnet** [comment]
Looks like this on my machine, happy to make changes, though.

screenshot-1548596076
screenshot-1548596063

**Comment by miku** [comment]
Nice!

**Comment by miku** [comment]
Quick local test:

* left/right margin on mobile is too small (for my taste)



* tags on small display are

**Comment by klingtnet** [comment]
Thank you very much! Will address that!

**Comment by klingtnet** [comment]
@miku Those two points should be fixed now.

**Comment by miku** [comment]
> @miku Those two points should be fixed now.

Yay. LGTM, let's merge so tags go live. Maybe add dark mode later.

**Pull request merged**
